### ISSUE TITLE
Line numbers misaligned

### ISSUE THREAD

**Issue by davwheat** [JoeGandy/ShareX-Custom-Upload#111]
It seems the line numbers for text uploads have become misaligned during style changes. (Also highlighting has stopped working?)

[![](https://u.davwheat.dev/c0MlVQ.png)](https://u.davwheat.dev/PwzTYE.js)

**Comment by theaquarium** [comment]
I'm not entirely sure what the issue is here. The CSS just seems to not work because it doesn't match what's in the repo. In @davwheat's CSS file, the `padding-top: 30px` line is before the `padding: 0 12px` so it gets overridden. @JoeGandy, if you can review the automatic updater PR, I can release a new version of the uploader which fixes a bunch of bugs and it should fix this.

**Comment by theaquarium** [comment]
Fixed by #105 I believe.
