### ISSUE TITLE
500 Error on V.2.1.1

### ISSUE THREAD

**Issue by Slddev** [JoeGandy/ShareX-Custom-Upload#149]
# Uploaded everything normally, did change config.php. Then this error keeps popping up in the apache error log:

`[core:alert] /var/www/vhosts/(root folder)/(sitename)/.htaccess: Option FollowSymLinks not allowed here`

**Comment by theaquarium** [comment]
This might be due to the fact that FollowSymLinks is disabled in your Apache server configuration.
You can fix this by changing the `Options +FollowSymLinks` line to say `Options +SymLinksIfOwnerMatch` in the `.htaccess` file at the root of the site, since some systems disable the FollowSymLinks option for security reasons.

Another solution is to make sure that `FollowSymLinks` is in the list of allowed options in the `AllowOverride` directive in your server config. However, the first solution will probably be better.
