### ISSUE TITLE
Since v2 the default naming isn't clear

### ISSUE THREAD

**Issue by JoeGandy** [JoeGandy/ShareX-Custom-Upload#88]
I'm just migrating my personal site,

By default the naming of the files doesn't take the shareX parameter?

This should be explained as we're changing the core simplicity of the program here

**Comment by JoeGandy** [comment]
Previously pre v2, we could pass in 'name' in the post options on shareX, allow us to name by shareXs custom name system. for me i use `%un_%h.%mi-%d.%mo.%yy_%remoji{2}`

Have we silently dropped support for this? I think the config.php doesnt explain this well at the moment

**Comment by theaquarium** [comment]
Yeah, sorry, I shouldn't have assumed people only use the ShareX name for dates. I replaced it with the `date` option for `default_naming_scheme`, but that doesn't support a bunch of other data that ShareX has. I think I could add another `default_naming_scheme` that is named something like `provided`, and this will use the name given in the `name` parameter by ShareX.

**Comment by JoeGandy** [comment]
Yeah i think the provided is a very good shout :)

**Comment by theaquarium** [comment]
I've started working on this change, but I feel like the way the config options are laid out right now could be confusing. Would it be better to instead have a config option for `sharex_upload_naming_scheme` with the options `keep`, `provided`, `date`, and `random`, another config option for `gallery_upload_naming_scheme` with `keep`, `date`, and `random`, and a third config entry for `text_upload_default_naming_scheme` with `date` and `random`?

This way, users would be able to choose which naming scheme to use for each upload type, since although you might want to use the name given by ShareX for ShareX uploads, it doesn't make sense to do this for gallery file and text uploads.

What do you think?
